INCLUDE (CheckIncludeFiles)

CHECK_INCLUDE_FILES(stdint.h   HAVE_STDINT_H)
CHECK_INCLUDE_FILES(stdlib.h   HAVE_STDLIB_H)
CHECK_INCLUDE_FILES(assert.h   HAVE_ASSERT_H)
CHECK_INCLUDE_FILES(execinfo.h HAVE_EXECINFO_H)

CONFIGURE_FILE(
  ${PROJECT_SOURCE_DIR}/include/Config.hh.cmake
  ${PROJECT_BINARY_DIR}/include/Config.hh)
