FIND_PROGRAM(IVERILOG_EXECUTABLE NAMES iverilog
  HINTS
  $ENV{PATH}
  PATH_SUFFIXES bin
  DOC "Icarus Verilog compiler iverilog"
)

FIND_PROGRAM(VVP_EXECUTABLE NAMES vvp
  HINTS
  $ENV{PATH}
  PATH_SUFFIXES bin
  DOC "Icarus Verilog simulation engine vvp"
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(IcarusVerilog DEFAULT_MSG
  IVERILOG_EXECUTABLE  VVP_EXECUTABLE)

MARK_AS_ADVANCED(IVERILOG_EXECUTABLE  VVP_EXECUTABLE)